USE ROLE DEV_ROLE_TRANSFORMATION;
USE DATABASE STG_DW;
SELECT 'DROP TABLE IF EXISTS ' || TABLE_CATALOG || '.' || TABLE_SCHEMA || '.' || TABLE_NAME || ';' AS CODE
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_CATALOG NOT IN ('SNOWFLAKE', 'INFORMATION_SCHEMA', 'PUBLIC')
AND TABLE_CATALOG IN ('STG_DW')
AND TABLE_SCHEMA LIKE 'DEV%'
AND TABLE_TYPE = 'BASE TABLE'
UNION
SELECT 'DROP VIEW IF EXISTS ' || TABLE_CATALOG || '.' || TABLE_SCHEMA || '.' || TABLE_NAME || ';' AS CODE
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_CATALOG NOT IN ('SNOWFLAKE', 'INFORMATION_SCHEMA', 'PUBLIC')
AND TABLE_CATALOG IN ('STG_DW')
AND TABLE_SCHEMA LIKE 'DEV%'
AND TABLE_TYPE = 'VIEW';

-------------------------------------------------------------------------------------------------------

COPY INTO @RAW.CITI_BIKE.AZURE_WEATHER_NY/weather
FROM (
    SELECT TIME_READABLE, CITY_NAME, COUNTRY, CITY_ID, CITY_FINDNAME, CITY_LATITUDE, CITY_LONGITUDE, CITY_LOCATION, 
    WEATHER_DESCRIPTION, WEATHER_MAIN, TEMPERATURE, HUMIDITY, PRESSURE, WIND_SPEED, WIND_DEG, METADATA_FILENAME, 
    METADATA_FILE_ROW_NUMBER, METADATA_FILE_LAST_MODIFIED
    FROM STG_DATASTORE.DBT_CCOELHO.STG_CITI_BIKE_WEATHER_NYC ORDER BY TIME_READABLE
)
FILE_FORMAT = (
    TYPE = 'CSV'
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    COMPRESSION = NONE
    FILE_EXTENSION = '.csv'
)
HEADER = TRUE
OVERWRITE = TRUE
SINGLE = FALSE;