USE ROLE ACCOUNTADMIN;
ALTER ACCOUNT SET TIMEZONE = 'Pacific/Auckland';

--------------------------------------------------------------------------
-- Storage Integrations
--------------------------------------------------------------------------
USE ROLE ACCOUNTADMIN;
CREATE STORAGE INTEGRATION citi_bike_storage_integration
  TYPE = EXTERNAL_STAGE
  STORAGE_PROVIDER = 'AZURE'
  ENABLED = TRUE
  AZURE_TENANT_ID = 'a51288de-b781-43b3-9666-50b41f408a2b'
  STORAGE_ALLOWED_LOCATIONS = ('azure://citibike4clay.blob.core.windows.net/citi-bike/');

--------------------------------------------------------------------------
-- IMPORTANT!!!
-- Perform the following steps manually
--------------------------------------------------------------------------

DESC STORAGE INTEGRATION citi_bike_storage_integration;

-- 1. Two important information here:
-- AZURE_CONSENT_URL
-- AZURE_MULTI_TENANT_APP_NAME

-- 2. Navigate to the AZURE_CONSENT_URL in a browser and click Accept to create the Snowflake service principal in your tenant.

-- 3. In the Azure portal, navigate to your Storage Account > Access Control (IAM) > Add role assignment.
-- Assign "Storage Blob Data Reader" for read-only access (loading data)
-- Search for the first characters in AZURE_MULTI_TENANT_APP_NAME noted earlier to find the correct service principal.

--------------------------------------------------------------------------
-- End of manual process. 
--------------------------------------------------------------------------

--------------------------------------------------------------------------
-- Roles
-- ROLE_INGESTION	Used for ingestion tools to ingest data into Snowflake Raw database only.
-- DEV_ROLE_TRANSFORMATION	Used by dbt for data transformation across Snowflake DEV databases.
-- TEST_ROLE_TRANSFORMATION	Used by dbt for data transformation across Snowflake TEST databases.
-- PROD_ROLE_TRANSFORMATION	Used by dbt for data transformation across Snowflake PROD databases.
-- PROD_ROLE_REPORT	Used by Power BI for querying Snowflake PROD DW database only.
--------------------------------------------------------------------------
USE ROLE SECURITYADMIN;
CREATE OR REPLACE ROLE ROLE_INGESTION;
GRANT ROLE ROLE_INGESTION TO ROLE SYSADMIN;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE ROLE_INGESTION;

USE ROLE ACCOUNTADMIN;
GRANT CREATE DATABASE ON ACCOUNT TO ROLE ROLE_INGESTION;

USE ROLE SECURITYADMIN;
CREATE OR REPLACE ROLE DEV_ROLE_TRANSFORMATION;
GRANT ROLE DEV_ROLE_TRANSFORMATION TO ROLE SYSADMIN;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE DEV_ROLE_TRANSFORMATION;

USE ROLE ACCOUNTADMIN;
GRANT CREATE DATABASE ON ACCOUNT TO ROLE DEV_ROLE_TRANSFORMATION;

USE ROLE SECURITYADMIN;
CREATE OR REPLACE ROLE TEST_ROLE_TRANSFORMATION;
GRANT ROLE TEST_ROLE_TRANSFORMATION TO ROLE SYSADMIN;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE TEST_ROLE_TRANSFORMATION;

USE ROLE ACCOUNTADMIN;
GRANT CREATE DATABASE ON ACCOUNT TO ROLE TEST_ROLE_TRANSFORMATION;

USE ROLE SECURITYADMIN;
CREATE OR REPLACE ROLE PROD_ROLE_TRANSFORMATION;
GRANT ROLE PROD_ROLE_TRANSFORMATION TO ROLE SYSADMIN;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE PROD_ROLE_TRANSFORMATION;

USE ROLE ACCOUNTADMIN;
GRANT CREATE DATABASE ON ACCOUNT TO ROLE PROD_ROLE_TRANSFORMATION;

USE ROLE SECURITYADMIN;
CREATE OR REPLACE ROLE PROD_ROLE_REPORT;
GRANT ROLE PROD_ROLE_REPORT TO ROLE SYSADMIN;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE PROD_ROLE_REPORT;

--------------------------------------------------------------------------
-- Databases
-- RAW.CITI_BIKE
-- STG_DATASTORE.TEST
-- STG_DATASTORE.PROD
-- DATASTORE.TEST
-- DATASTORE.PROD
-- STG_DW.TEST
-- STG_DW.PROD
-- DW.TEST
-- DW.PROD
-- DBT_PROJECT_EVALUATOR.TEST
-- DBT_PROJECT_EVALUATOR.PROD
--------------------------------------------------------------------------
USE ROLE ROLE_INGESTION;
CREATE OR REPLACE DATABASE RAW;
CREATE OR REPLACE SCHEMA CITI_BIKE;

GRANT USAGE ON DATABASE RAW TO ROLE DEV_ROLE_TRANSFORMATION;
GRANT USAGE ON SCHEMA RAW.CITI_BIKE TO ROLE DEV_ROLE_TRANSFORMATION;
GRANT SELECT ON ALL TABLES IN SCHEMA RAW.CITI_BIKE TO ROLE DEV_ROLE_TRANSFORMATION;

GRANT USAGE ON DATABASE RAW TO ROLE TEST_ROLE_TRANSFORMATION;
GRANT USAGE ON SCHEMA RAW.CITI_BIKE TO ROLE TEST_ROLE_TRANSFORMATION;
GRANT SELECT ON ALL TABLES IN SCHEMA RAW.CITI_BIKE TO ROLE TEST_ROLE_TRANSFORMATION;

GRANT USAGE ON DATABASE RAW TO ROLE PROD_ROLE_TRANSFORMATION;
GRANT USAGE ON SCHEMA RAW.CITI_BIKE TO ROLE PROD_ROLE_TRANSFORMATION;
GRANT SELECT ON ALL TABLES IN SCHEMA RAW.CITI_BIKE TO ROLE PROD_ROLE_TRANSFORMATION;

USE ROLE SECURITYADMIN; 
GRANT SELECT ON FUTURE TABLES IN SCHEMA RAW.CITI_BIKE TO ROLE DEV_ROLE_TRANSFORMATION;
GRANT SELECT ON FUTURE TABLES IN SCHEMA RAW.CITI_BIKE TO ROLE TEST_ROLE_TRANSFORMATION;
GRANT SELECT ON FUTURE TABLES IN SCHEMA RAW.CITI_BIKE TO ROLE PROD_ROLE_TRANSFORMATION;

USE ROLE SYSADMIN;
CREATE OR REPLACE DATABASE STG_DATASTORE;
CREATE SCHEMA STG_DATASTORE.TEST;
CREATE SCHEMA STG_DATASTORE.PROD;

CREATE OR REPLACE DATABASE DATASTORE;
CREATE SCHEMA DATASTORE.TEST;
CREATE SCHEMA DATASTORE.PROD;

CREATE OR REPLACE DATABASE STG_DW;
CREATE SCHEMA STG_DW.TEST;
CREATE SCHEMA STG_DW.PROD;

CREATE OR REPLACE DATABASE DW;
CREATE SCHEMA DW.TEST;
CREATE SCHEMA DW.PROD;

CREATE OR REPLACE DATABASE DBT_PROJECT_EVALUATOR;
CREATE SCHEMA DBT_PROJECT_EVALUATOR.TEST;
CREATE SCHEMA DBT_PROJECT_EVALUATOR.PROD;

GRANT USAGE ON DATABASE STG_DATASTORE TO ROLE DEV_ROLE_TRANSFORMATION;
GRANT USAGE ON DATABASE STG_DATASTORE TO ROLE TEST_ROLE_TRANSFORMATION;
GRANT USAGE ON DATABASE STG_DATASTORE TO ROLE PROD_ROLE_TRANSFORMATION;

GRANT USAGE ON DATABASE DATASTORE TO ROLE DEV_ROLE_TRANSFORMATION;
GRANT USAGE ON DATABASE DATASTORE TO ROLE TEST_ROLE_TRANSFORMATION;
GRANT USAGE ON DATABASE DATASTORE TO ROLE PROD_ROLE_TRANSFORMATION;

GRANT USAGE ON DATABASE STG_DW TO ROLE DEV_ROLE_TRANSFORMATION;
GRANT USAGE ON DATABASE STG_DW TO ROLE TEST_ROLE_TRANSFORMATION;
GRANT USAGE ON DATABASE STG_DW TO ROLE PROD_ROLE_TRANSFORMATION;

GRANT USAGE ON DATABASE DW TO ROLE DEV_ROLE_TRANSFORMATION;
GRANT USAGE ON DATABASE DW TO ROLE TEST_ROLE_TRANSFORMATION;
GRANT USAGE ON DATABASE DW TO ROLE PROD_ROLE_TRANSFORMATION;
GRANT USAGE ON DATABASE DW TO ROLE PROD_ROLE_REPORT;

GRANT USAGE ON DATABASE DBT_PROJECT_EVALUATOR TO ROLE DEV_ROLE_TRANSFORMATION;
GRANT USAGE ON DATABASE DBT_PROJECT_EVALUATOR TO ROLE TEST_ROLE_TRANSFORMATION;
GRANT USAGE ON DATABASE DBT_PROJECT_EVALUATOR TO ROLE PROD_ROLE_TRANSFORMATION;

GRANT ALL ON SCHEMA STG_DATASTORE.TEST TO ROLE TEST_ROLE_TRANSFORMATION;
GRANT ALL ON SCHEMA DATASTORE.TEST TO ROLE TEST_ROLE_TRANSFORMATION;
GRANT ALL ON SCHEMA STG_DW.TEST TO ROLE TEST_ROLE_TRANSFORMATION;
GRANT ALL ON SCHEMA DW.TEST TO ROLE TEST_ROLE_TRANSFORMATION;
GRANT ALL ON SCHEMA DBT_PROJECT_EVALUATOR.TEST TO ROLE TEST_ROLE_TRANSFORMATION;

GRANT ALL ON SCHEMA STG_DATASTORE.PROD TO ROLE PROD_ROLE_TRANSFORMATION;
GRANT ALL ON SCHEMA DATASTORE.PROD TO ROLE PROD_ROLE_TRANSFORMATION;
GRANT ALL ON SCHEMA STG_DW.PROD TO ROLE PROD_ROLE_TRANSFORMATION;
GRANT ALL ON SCHEMA DW.PROD TO ROLE PROD_ROLE_TRANSFORMATION;
GRANT ALL ON SCHEMA DBT_PROJECT_EVALUATOR.PROD TO ROLE PROD_ROLE_TRANSFORMATION;


GRANT USAGE ON SCHEMA DW.PROD TO ROLE PROD_ROLE_REPORT;

USE ROLE SECURITYADMIN; 
GRANT SELECT ON FUTURE TABLES IN SCHEMA DW.PROD TO ROLE PROD_ROLE_REPORT;


--------------------------------------------------------------------------
-- dbt-specifc user
--------------------------------------------------------------------------

USE ROLE SYSADMIN;
CREATE SCHEMA STG_DATASTORE.DBT_CCOELHO;
CREATE SCHEMA DATASTORE.DBT_CCOELHO;
CREATE SCHEMA STG_DW.DBT_CCOELHO;
CREATE SCHEMA DW.DBT_CCOELHO;
CREATE SCHEMA DBT_PROJECT_EVALUATOR.DBT_CCOELHO;

GRANT ALL ON SCHEMA STG_DATASTORE.DBT_CCOELHO TO ROLE DEV_ROLE_TRANSFORMATION;
GRANT ALL ON SCHEMA DATASTORE.DBT_CCOELHO TO ROLE DEV_ROLE_TRANSFORMATION;
GRANT ALL ON SCHEMA STG_DW.DBT_CCOELHO TO ROLE DEV_ROLE_TRANSFORMATION;
GRANT ALL ON SCHEMA DW.DBT_CCOELHO TO ROLE DEV_ROLE_TRANSFORMATION;
GRANT ALL ON SCHEMA DBT_PROJECT_EVALUATOR.DBT_CCOELHO TO ROLE DEV_ROLE_TRANSFORMATION;


--------------------------------------------------------------------------
-- Stages and File Formats
--------------------------------------------------------------------------

USE ROLE ROLE_INGESTION;
CREATE OR REPLACE STAGE RAW.CITI_BIKE.AZURE_CITI_BIKE
STORAGE_INTEGRATION = citi_bike_storage_integration
URL = 'azure://citibike4clay.blob.core.windows.net/citi-bike/';

CREATE OR REPLACE STAGE RAW.CITI_BIKE.S3_NYC_WEATHER
url = 's3://snowflake-workshop-lab/weather-nyc';

CREATE OR REPLACE FILE FORMAT RAW.CITI_BIKE.FF_CSV_01
    TYPE = CSV
    FIELD_DELIMITER = ','
    NULL_IF = ('NULL', 'null')
    EMPTY_FIELD_AS_NULL = true
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    TRIM_SPACE = TRUE
    PARSE_HEADER = TRUE -- Important for match_by_column_name.
    ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE; -- This is important for INCLUDE_METADATA.

CREATE OR REPLACE FILE FORMAT RAW.CITI_BIKE.FF_JSON_01
    TYPE = 'JSON';

--------------------------------------------------------------------------
-- Create RAW Tables
--------------------------------------------------------------------------

-- This table has ENABLE_SCHEMA_EVOLUTION. 
-- The column names will be added automatically based on the source files.
CREATE OR REPLACE TABLE RAW.CITI_BIKE.TRIPS 
ENABLE_SCHEMA_EVOLUTION = TRUE (
    METADATA_FILENAME STRING, 
    METADATA_FILE_ROW_NUMBER INT, 
    METADATA_FILE_LAST_MODIFIED TIMESTAMP
);

CREATE OR REPLACE TABLE RAW.CITI_BIKE.WEATHER_NYC (
	DATA VARIANT,
    METADATA_FILENAME STRING, 
    METADATA_FILE_ROW_NUMBER INT, 
    METADATA_FILE_LAST_MODIFIED TIMESTAMP
);


--------------------------------------------------------------------------
--Ingest data
--------------------------------------------------------------------------

COPY INTO RAW.CITI_BIKE.TRIPS 
FROM @RAW.CITI_BIKE.AZURE_CITI_BIKE
FILE_FORMAT = (FORMAT_NAME = 'RAW.CITI_BIKE.FF_CSV_01')
PATTERN = '.*citibike-tripdata_.*[.]csv'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
INCLUDE_METADATA = (
    METADATA_FILENAME = METADATA$FILENAME,
    METADATA_FILE_ROW_NUMBER = METADATA$FILE_ROW_NUMBER,
    METADATA_FILE_LAST_MODIFIED = METADATA$FILE_LAST_MODIFIED
);

COPY INTO RAW.CITI_BIKE.WEATHER_NYC from (
    SELECT 
        $1
        ,METADATA$FILENAME, METADATA$FILE_ROW_NUMBER, METADATA$FILE_LAST_MODIFIED
    FROM @RAW.CITI_BIKE.S3_NYC_WEATHER
    (FILE_FORMAT => 'RAW.CITI_BIKE.FF_JSON_01', PATTERN => '.*weather_.*[.]json[.]gz')
);

--------------------------------------------------------------------------
--END
--------------------------------------------------------------------------