USE ROLE ACCOUNTADMIN;

USE WAREHOUSE COMPUTE_WH;

ALTER ACCOUNT SET TIMEZONE = 'Pacific/Auckland';

--------------------------------------------------------------------------
--Roles
--------------------------------------------------------------------------

CREATE OR REPLACE ROLE ROLE_INGESTION;
GRANT ROLE ROLE_INGESTION TO ROLE SYSADMIN;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE ROLE_INGESTION;
GRANT CREATE DATABASE ON ACCOUNT TO ROLE ROLE_INGESTION;

CREATE OR REPLACE ROLE DEV_ROLE_TRANSFORMATION;
GRANT ROLE DEV_ROLE_TRANSFORMATION TO ROLE SYSADMIN;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE DEV_ROLE_TRANSFORMATION;
GRANT CREATE DATABASE ON ACCOUNT TO ROLE DEV_ROLE_TRANSFORMATION;

CREATE OR REPLACE ROLE TEST_ROLE_TRANSFORMATION;
GRANT ROLE TEST_ROLE_TRANSFORMATION TO ROLE SYSADMIN;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE TEST_ROLE_TRANSFORMATION;
GRANT CREATE DATABASE ON ACCOUNT TO ROLE TEST_ROLE_TRANSFORMATION;

CREATE OR REPLACE ROLE PROD_ROLE_TRANSFORMATION;
GRANT ROLE PROD_ROLE_TRANSFORMATION TO ROLE SYSADMIN;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE PROD_ROLE_TRANSFORMATION;
GRANT CREATE DATABASE ON ACCOUNT TO ROLE PROD_ROLE_TRANSFORMATION;


--------------------------------------------------------------------------
--Databases
--------------------------------------------------------------------------


USE ROLE ROLE_INGESTION;
CREATE OR REPLACE DATABASE RAW;
CREATE OR REPLACE SCHEMA CITI_BIKE;

GRANT USAGE ON DATABASE RAW TO ROLE DEV_ROLE_TRANSFORMATION;
GRANT USAGE ON SCHEMA RAW.CITI_BIKE TO ROLE DEV_ROLE_TRANSFORMATION;
GRANT SELECT ON ALL TABLES IN SCHEMA RAW.CITI_BIKE TO ROLE DEV_ROLE_TRANSFORMATION;

GRANT USAGE ON DATABASE RAW TO ROLE TEST_ROLE_TRANSFORMATION;
GRANT USAGE ON SCHEMA RAW.CITI_BIKE TO ROLE TEST_ROLE_TRANSFORMATION;
GRANT SELECT ON ALL TABLES IN SCHEMA RAW.CITI_BIKE TO ROLE TEST_ROLE_TRANSFORMATION;

GRANT USAGE ON DATABASE RAW TO ROLE PROD_ROLE_TRANSFORMATION;
GRANT USAGE ON SCHEMA RAW.CITI_BIKE TO ROLE PROD_ROLE_TRANSFORMATION;
GRANT SELECT ON ALL TABLES IN SCHEMA RAW.CITI_BIKE TO ROLE PROD_ROLE_TRANSFORMATION;

USE ROLE SECURITYADMIN; 
GRANT SELECT ON FUTURE TABLES IN SCHEMA RAW.CITI_BIKE TO ROLE DEV_ROLE_TRANSFORMATION;
GRANT SELECT ON FUTURE TABLES IN SCHEMA RAW.CITI_BIKE TO ROLE TEST_ROLE_TRANSFORMATION;
GRANT SELECT ON FUTURE TABLES IN SCHEMA RAW.CITI_BIKE TO ROLE PROD_ROLE_TRANSFORMATION;

USE ROLE PROD_ROLE_TRANSFORMATION;
CREATE OR REPLACE DATABASE STG_DATASTORE;
CREATE SCHEMA DEV;
CREATE SCHEMA TEST;
CREATE SCHEMA PROD;
CREATE SCHEMA DBT_CCOELHO;

CREATE OR REPLACE DATABASE DATASTORE;
CREATE SCHEMA DEV;
CREATE SCHEMA TEST;
CREATE SCHEMA PROD;
CREATE SCHEMA DBT_CCOELHO;

CREATE OR REPLACE DATABASE STG_DW;
CREATE SCHEMA DEV;
CREATE SCHEMA TEST;
CREATE SCHEMA PROD;
CREATE SCHEMA DBT_CCOELHO;

CREATE OR REPLACE DATABASE DW;
CREATE SCHEMA DEV;
CREATE SCHEMA TEST;
CREATE SCHEMA PROD;
CREATE SCHEMA DBT_CCOELHO;

GRANT USAGE ON DATABASE STG_DATASTORE TO ROLE DEV_ROLE_TRANSFORMATION;
GRANT USAGE ON DATABASE STG_DATASTORE TO ROLE TEST_ROLE_TRANSFORMATION;

GRANT USAGE ON DATABASE DATASTORE TO ROLE DEV_ROLE_TRANSFORMATION;
GRANT USAGE ON DATABASE DATASTORE TO ROLE TEST_ROLE_TRANSFORMATION;

GRANT USAGE ON DATABASE STG_DW TO ROLE DEV_ROLE_TRANSFORMATION;
GRANT USAGE ON DATABASE STG_DW TO ROLE TEST_ROLE_TRANSFORMATION;

GRANT USAGE ON DATABASE DW TO ROLE DEV_ROLE_TRANSFORMATION;
GRANT USAGE ON DATABASE DW TO ROLE TEST_ROLE_TRANSFORMATION;

GRANT ALL ON SCHEMA STG_DATASTORE.TEST TO ROLE TEST_ROLE_TRANSFORMATION;
GRANT ALL ON SCHEMA DATASTORE.TEST TO ROLE TEST_ROLE_TRANSFORMATION;
GRANT ALL ON SCHEMA STG_DW.TEST TO ROLE TEST_ROLE_TRANSFORMATION;
GRANT ALL ON SCHEMA DW.TEST TO ROLE TEST_ROLE_TRANSFORMATION;

GRANT ALL ON SCHEMA STG_DATASTORE.DEV TO ROLE DEV_ROLE_TRANSFORMATION;
GRANT ALL ON SCHEMA DATASTORE.DEV TO ROLE DEV_ROLE_TRANSFORMATION;
GRANT ALL ON SCHEMA STG_DW.DEV TO ROLE DEV_ROLE_TRANSFORMATION;
GRANT ALL ON SCHEMA DW.DEV TO ROLE DEV_ROLE_TRANSFORMATION;

GRANT ALL ON SCHEMA STG_DATASTORE.DBT_CCOELHO TO ROLE DEV_ROLE_TRANSFORMATION;
GRANT ALL ON SCHEMA DATASTORE.DBT_CCOELHO TO ROLE DEV_ROLE_TRANSFORMATION;
GRANT ALL ON SCHEMA STG_DW.DBT_CCOELHO TO ROLE DEV_ROLE_TRANSFORMATION;
GRANT ALL ON SCHEMA DW.DBT_CCOELHO TO ROLE DEV_ROLE_TRANSFORMATION;


--------------------------------------------------------------------------
--Stages and File Formats
--------------------------------------------------------------------------

USE ROLE ROLE_INGESTION;
CREATE OR REPLACE STAGE RAW.CITI_BIKE.AZURE_CITI_BIKE
URL = 'azure://CHANGE_ME.blob.core.windows.net/citi-bike/data/'
CREDENTIALS = (
    AZURE_SAS_TOKEN = 'sp=CHANGE_ME');

CREATE OR REPLACE STAGE RAW.CITI_BIKE.S3_NYC_WEATHER
url = 's3://snowflake-workshop-lab/weather-nyc';

CREATE OR REPLACE FILE FORMAT RAW.CITI_BIKE.FF_CSV_01
    TYPE = CSV
    FIELD_DELIMITER = ','
    SKIP_HEADER = 1
    NULL_IF = ('NULL', 'null')
    EMPTY_FIELD_AS_NULL = true
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    TRIM_SPACE = TRUE;

CREATE OR REPLACE FILE FORMAT RAW.CITI_BIKE.FF_JSON_01
    TYPE = 'JSON';


--------------------------------------------------------------------------
--Create Tables
--------------------------------------------------------------------------
    

CREATE OR REPLACE TABLE RAW.CITI_BIKE.TRIPS (
	TRIPDURATION NUMBER(38,0),
	STARTTIME TIMESTAMP_NTZ(9),
	STOPTIME TIMESTAMP_NTZ(9),
	START_STATION_ID NUMBER(38,0),
    START_STATION_NAME STRING,
    START_STATION_LATITUDE FLOAT,
    START_STATION_LONGITUDE FLOAT,
	END_STATION_ID NUMBER(38,0),
    END_STATION_NAME STRING,
    END_STATION_LATITUDE FLOAT,
    END_STATION_LONGITUDE FLOAT,
	BIKEID NUMBER(38,0),
	USERTYPE STRING,
	BIRTH_YEAR NUMBER(38,0),
	GENDER NUMBER(38,0), 
    METADATA_FILENAME STRING, 
    METADATA_FILE_ROW_NUMBER INT, 
    METADATA_FILE_LAST_MODIFIED TIMESTAMP
);

CREATE OR REPLACE TABLE RAW.CITI_BIKE.WEATHER_NYC (
	DATA VARIANT,
    METADATA_FILENAME STRING, 
    METADATA_FILE_ROW_NUMBER INT, 
    METADATA_FILE_LAST_MODIFIED TIMESTAMP
);


--------------------------------------------------------------------------
--Ingest data
--------------------------------------------------------------------------

USE ROLE ROLE_INGESTION;
COPY INTO RAW.CITI_BIKE.TRIPS from (
    SELECT 
        $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15
        ,METADATA$FILENAME, METADATA$FILE_ROW_NUMBER, METADATA$FILE_LAST_MODIFIED
    FROM @RAW.CITI_BIKE.AZURE_CITI_BIKE
    (FILE_FORMAT => 'RAW.CITI_BIKE.FF_CSV_01', PATTERN => '.*trips*.*csv.*')
);


COPY INTO RAW.CITI_BIKE.WEATHER_NYC from (
    SELECT 
        $1
        ,METADATA$FILENAME, METADATA$FILE_ROW_NUMBER, METADATA$FILE_LAST_MODIFIED
    FROM @RAW.CITI_BIKE.S3_NYC_WEATHER
    (FILE_FORMAT => 'RAW.CITI_BIKE.FF_JSON_01', PATTERN => '.*weather*.*json.*')
);


--------------------------------------------------------------------------
--END
--------------------------------------------------------------------------
